### ISSUE TITLE
server down

### ISSUE THREAD

**Issue by shdudwns** [RockyTeam-eng/Rocky#2]
[root@localhost pm1]# ./st*
./bin/php7/bin/php: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory

**Comment by caspervanneck** [comment]
php eror not software

**Comment by shdudwns** [comment]
Other drivers work, but they're not synchronized.

2017. 5. 28. 오후 8:03에 "wesleyvanneck" <notifications@github.com>님이 작성:

**Comment by caspervanneck** [comment]
okey
