### ISSUE TITLE
Does Redstone work?

### ISSUE THREAD

**Issue by shdudwns** [RockyTeam-eng/Rocky#3]
I saw that there is Rocky.yml

**Comment by shdudwns** [comment]
I have tested it and it does not work. Or remove or modify the Redstone source. If it does not work, it takes more leaks.
@caspervanneck

**Comment by shdudwns** [comment]
Red stone won't work.
Please fix the red stone part.

**Comment by shdudwns** [comment]
@caspervanneck

**Comment by caspervanneck** [comment]
yape that is that its auto of it give erors

**Comment by shdudwns** [comment]
Is Redstone working when I fix that error?
