### ISSUE TITLE
AI Move

### ISSUE THREAD

**Issue by XxParkerGamesxX** [RockyTeam-eng/Rocky#4]
Add all ImagicalMineReactive AI to this one

**Comment by caspervanneck** [comment]
Yea

**Comment by shdudwns** [comment]
ai:
 #AI switch
 enable: false
 #Zombie'AI，0=disabled，1=AI 1.0ver，2=new AI(Faultiness)
 zombie: 1
 #PigZombie's AI
 pigzombie: true
 #the AI of cow and mushroom cow
 cow: true
 #Chicken's AI
 chicken: true
 #Sheep's AI
 sheep: true
 #Pigs' AI
 pig: true
 #Skeleton's AI
 skeleton: true
 #Creeper's AI
 creeper: true
 #Iron golem's AI
 iron-golem: true
 #Snow golem's AI
 snow-golem: true
 #Destory blocks if creeper exploded
 creeper-explode-destroy-block: false
 #Choose if allow mob auto generate
 mobgenerate: false

**Comment by shdudwns** [comment]
But monster AI activation enabled, but there are too many monsters and there are too many errors.

**Comment by caspervanneck** [comment]
that to old and its removet

**Comment by shdudwns** [comment]
What is the function called AI?
Do not you have to destroy the entity AI if you do not use it?
@caspervanneck
