### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shdudwns** [RockyTeam-eng/Rocky#5]
Notice: Undefined property: pocketmine\entity\Minecart::$ridingEntity in /root/pm1/src/pocketmine/entity/Minecart.php on line 143

Notice: Undefined property: pocketmine\entity\Minecart::$ridingEntity in /root/pm1/src/pocketmine/entity/Minecart.php on line 143

Notice: Undefined property: pocketmine\entity\Minecart::$ridingEntity in /root/pm1/src/pocketmine/entity/Minecart.php on line 208

Notice: Undefined property: pocketmine\entity\Minecart::$ridingEntity in /root/pm1/src/pocketmine/entity/Minecart.php on line 265

Notice: Undefined property: pocketmine\entity\Minecart::$ridingEntity in /root/pm1/src/pocketmine/entity/Minecart.php on line 389

**Comment by shdudwns** [comment]
@caspervanneck

**Comment by caspervanneck** [comment]
Yep that one of the bugs

**Comment by caspervanneck** [comment]
fixt
