### ISSUE TITLE
Take this away.

### ISSUE THREAD

**Issue by shdudwns** [RockyTeam-eng/Rocky#7]
level:
 #날씨 시스템을 켜는 경우 설정하세요
 weather: true
 #날씨 랜덤 기간
 weather-random-duration-min: 6000
 weather-random-duration-max: 12000
 #랜덤 번개 치는 주기，기본은 10초, 0 = 비활성화
 lightning-time: 200
 #번개가 불과 함께 치게 하려는 경우 설정하세요
 lightning-fire: false
 #불이 번지는 것을 활성화 하려는 경우 설정하세요
 fire-spread: false
 
player:
 #배고픔 시스템 스위치
 hunger: true
 #경험치 시스템을 켜는 경우 고르세요
 experience: true
 #플레이어가 사망하였을때 인벤토리를 유지하려는 경우 고르세요
 keep-inventory: false
 #게임 모드를 크리에이티브로 변경하는 경우 자동으로 인벤토리를 비웁니다
 auto-clear-inventory : true
 #플레이어가 사망하였을때 경험치를 유지하려는 경우 고르세요
 keep-experience: false
 #플레이어들이 참여했을때 크래시가 발생하는 경우, 이 값을 10 이하로 설정하세요. 비활성화=-1
 chunk-radius: -1

nether:
 #지옥이 허용된 경우 고르세요. 지옥 레벨이 자동으로 생성됩니다.
 allow-nether: true
 #지옥 레벨의 이름
 level-name: "nether"
 
server:
 #철 골램을 생성하는 것이 허용된 경우 고르세요
 allow-iron-golem: false
 #눈 골렘을 생성하는 것이 허용된 경우 고르세요
 allow-snow-golem: false
 #server.log를 비활성화 하는 경우 고르세요
 disable-log: false
 #자동 비행 방지를 활성화 하는 경우 고르세요
 anti-fly: true
 #비동기 청크 요청을 활성화 하는 경우 고르세요
 async-chunk-request: true
 #플레이어가 참여할 때 뜨는 메시지를 고릅니다
 #0 = 메시지, 1 = 팁, 2 = 팝업
 player-msg-type: 0
 login-msg: "§3@player님이 게임에 참여했습니다"
 logout-msg: "§3@player님이 게임을 떠났습니다"
 #움직임 확인을 활성화 하는 경우 고르세요 (더 이상 뒤로 당겨지지 않음)
 check-movement: true
 #제한된 크리에이티브를 활성화 하는 경우 설정하세요 (아이템 드롭 불가, 상자 열기 불가 등)
 limited-creative: true
 #블럭 파괴 파티클을 추가하는 경우 설정하세요
 destroy-block-particle: true
 #투척용 포션을 활성화 하는 경우 고르세요
 allow-splash-potion: true
 #고급 명령어 선택기를 활성화 하는 경우 설정하세요
 advanced-command-selector: false

enchantment:
 #모루가 허용된 경우 고르세요
 enable-anvil: true
 #마법 부여대가 허용된 경우 고르세요
 enable-enchanting-table: true
 #책장의 수를 세려는 경우 활성화 하세요. 서버 랙을 유발할 수도 있습니다.
 #만약 이 옵션이 false인 경우, 서버는 랜덤 카운트를 사용할 것 입니다 (0~15)
 count-bookshelf: false

redstone:
 ################################################
 ######레드스톤 시스템이 허용된 경우 고르세요#######
 ################################################
 #만약 true가 아닌 경우 레드스톤이 작동하지 않습니다#
 ################################################
 enable: false
 #주파수 펄스를 허용하는 경우 고르세요
 frequency-pulse: false
 #펄스 주파수 설정, 기본: 1초
 pulse-frequency: 1

dserver:
 #모든 멀티 (다중) 서버의 수 통합
 enable: false
 #자동으로 쿼리 업데이트
 query-auto-update: false
 #쿼리 업데이트 주기
 query-tick-update: true
 #Motd 최대 플레이어 숫자
 motd-max-players: 0
 #쿼리 최대 플레이어 숫자，0=기본
 query-max-players: 0
 #motd에서 모든 플레이어의 숫자 표시
 motd-all-players: false
 #쿼리에서 모든 플레이어의 숫자 표시
 query-all-players: false
 #motd에서 온라인 플레이어의 숫자 표시
 motd-players: false
 #쿼리에서 온라인 플레이어의 숫자 표시
 query-players: false
 #업데이트 주기, 20=1초
 time: 40
 #실패한 경우 다시 시도할 빈도
 retry-times: 3
 #서버 목록，';'를 사용하여 분리하세요，예시: 1.example.com:19132;2.example.com:19133
 server-list: ""

inventory:
 #모루와 관련된 문제가 있는 경우 true로 설정하세요. 인벤토리 처리를 vanila fashion (기본 방식)으로 치트 방지나 확인 없이 진행합니다.
 allow-cheats: false

**Comment by caspervanneck** [comment]
Nope

**Comment by shdudwns** [comment]
Please add Korean language.
@caspervanneck
